server:
  #7开头一般就是注册中心  8开头就是服务提供者  9开头就是服务消费者
  port: 9001
#注册给注册中心  取名
spring:
  application:
    name: springcloud-crm
eureka:
  instance:
    #eureka服务在接收到最后一个心跳等待的时间，然后才能把当前服务从列表中删除
    lease-expiration-duration-in-seconds: 10
    #客户端需要向服务器发送的频率
    lease-renewal-interval-in-seconds: 1
    #显示客服端的真实ip
    prefer-ip-address: true
  client:
    #不在注册中心显示服务消费者
    register-with-eureka: false
    service-url:
      #告诉服务提供者把要注册的服务注册到哪  7001为Eureka服务器端口
     defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
feign:
  hystrix:
    enabled: true
    #支持开启熔断
